#!/usr/bin/env python3
"""
Script para gerar automaticamente o index.html dos assets.
Escaneia a pasta images/ e cria uma galeria visual de todas as imagens.
"""

import os
import json
from pathlib import Path

BASE_URL = "https://wesleysza1.github.io/legends_card_game/images"
IMAGES_DIR = Path("images")

def scan_images():
    """Escaneia a pasta images/ e retorna um dicionário organizado por subpasta."""
    assets = {}
    
    if not IMAGES_DIR.exists():
        print(f"❌ Pasta {IMAGES_DIR} não encontrada!")
        return assets
    
    for subfolder in sorted(IMAGES_DIR.iterdir()):
        if subfolder.is_dir():
            folder_name = subfolder.name
            images = sorted([
                f.name for f in subfolder.iterdir() 
                if f.is_file() and f.suffix.lower() in ['.png', '.jpg', '.jpeg', '.webp']
            ])
            if images:
                assets[folder_name] = images
    
    return assets

def generate_html(assets):
    """Gera o HTML da página de navegação dos assets."""
    
    folders_html = ""
    for folder, files in assets.items():
        folder_title = folder.capitalize()
        count = len(files)
        folders_html += f'''
    <div class="folder">
        <div class="folder-title">📁 {folder_title} ({count})</div>
        <div class="gallery" id="{folder}"></div>
    </div>
'''
    
    assets_json = json.dumps(assets, indent=12)
    
    html = f'''<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Legends - Assets Browser</title>
    <style>
        * {{
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }}
        body {{
            font-family: Arial, sans-serif;
            background: #1a1a1a;
            color: #fff;
            padding: 20px;
        }}
        h1 {{
            text-align: center;
            margin-bottom: 30px;
            color: #ffd700;
        }}
        .folder {{
            margin-bottom: 40px;
        }}
        .folder-title {{
            font-size: 24px;
            color: #ffd700;
            margin-bottom: 15px;
            padding-bottom: 10px;
            border-bottom: 2px solid #ffd700;
        }}
        .gallery {{
            display: grid;
            grid-template-columns: repeat(auto-fill, minmax(200px, 1fr));
            gap: 20px;
        }}
        .image-card {{
            background: #2a2a2a;
            border-radius: 8px;
            padding: 10px;
            text-align: center;
            transition: transform 0.2s;
        }}
        .image-card:hover {{
            transform: scale(1.05);
            background: #3a3a3a;
        }}
        .image-card img {{
            width: 100%;
            height: 200px;
            object-fit: contain;
            border-radius: 4px;
            background: #fff;
        }}
        .image-name {{
            margin-top: 10px;
            font-size: 12px;
            color: #ccc;
            word-break: break-word;
        }}
        .copy-btn {{
            margin-top: 8px;
            padding: 5px 10px;
            background: #ffd700;
            color: #1a1a1a;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            font-size: 11px;
        }}
        .copy-btn:hover {{
            background: #ffed4e;
        }}
        .footer {{
            text-align: center;
            margin-top: 50px;
            color: #666;
            font-size: 12px;
        }}
    </style>
</head>
<body>
    <h1>🎴 Legends Card Game - Assets</h1>
    {folders_html}
    <div class="footer">
        Auto-generated by build_assets_index.py
    </div>

    <script>
        const BASE_URL = '{BASE_URL}';
        
        const assets = {assets_json};

        function copyToClipboard(text) {{
            navigator.clipboard.writeText(text).then(() => {{
                alert('URL copiada: ' + text);
            }});
        }}

        function renderGallery(folder, files) {{
            const container = document.getElementById(folder);
            files.forEach(file => {{
                const url = `${{BASE_URL}}/${{folder}}/${{file}}`;
                const card = document.createElement('div');
                card.className = 'image-card';
                card.innerHTML = `
                    <img src="${{url}}" alt="${{file}}" loading="lazy">
                    <div class="image-name">${{file}}</div>
                    <button class="copy-btn" onclick="copyToClipboard('${{url}}')">📋 Copiar URL</button>
                `;
                container.appendChild(card);
            }});
        }}

        Object.keys(assets).forEach(folder => {{
            renderGallery(folder, assets[folder]);
        }});

        window.copyToClipboard = copyToClipboard;
    </script>
</body>
</html>'''
    
    return html

def main():
    print("🔍 Escaneando pasta images/...")
    assets = scan_images()
    
    if not assets:
        print("⚠️  Nenhuma imagem encontrada!")
        return
    
    total_images = sum(len(files) for files in assets.values())
    print(f"✅ Encontradas {total_images} imagens em {len(assets)} pastas")
    
    print("📝 Gerando index.html...")
    html = generate_html(assets)
    
    output_path = IMAGES_DIR / "index.html"
    output_path.write_text(html, encoding='utf-8')
    
    print(f"✅ Arquivo gerado: {output_path}")
    print("\n📋 Resumo:")
    for folder, files in assets.items():
        print(f"   {folder}: {len(files)} imagens")

if __name__ == "__main__":
    main()
